# Generated by Django 3.2.9 on 2022-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preview',
            name='image',
            field=models.FilePathField(path='/home'),
        ),
    ]
